export const OPEN_DIALOG = 'OPEN_DIALOG';
export const OPEN_SIDEBAR_MENU = 'OPEN_SIDEBAR_MENU';
export const CLOSE_SIDEBAR_MENU = 'CLOSE_SIDEBAR_MENU';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const REFRESH = 'REFRESH';
export const ADD_CARD = 'ADD_CARD';
export const DELETE_CARD = 'DELETE_CARD';

// LOGIN/SIGN-UP

export const SESSION_RESTORING = 'SESSION_RESTORING'
export const SESSION_LOADING = 'SESSION_LOADING'
export const SESSION_SUCCESS = 'SESSION_SUCCESS'
export const SESSION_ERROR = 'SESSION_ERROR'
export const SESSION_LOGOUT = 'SESSION_LOGOUT'
